package.json, src/externalContext.ts, src/legacyQuizHandling/old-questions.test.ts, src/legacyQuizHandling/old-questions.ts, src/legacyQuizHandling/simpleComprehensionQuiz.js
This required a change to the organization of elements that Bloom generates for a quiz answer, and hence changes to BP's old-questions code, and a new version of the quiz JS. A breaking change, so I moved it up to 0.9. Also cleaned up some problems with postMessage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/17)
=> BL-7192 Support material design check boxes

src/bloom-player.less, src/bloomPlayerTheme.ts, src/controlBar.tsx
Be more elegant to control this with theme somehow, but can't find a way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/19)
=> BL-7273 Adjust app bar colors

package.json, src/bloom-player-controls.tsx
* Don't Play/Pause when tapping/clicking on the screen
if there's no media on the page
* bump version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/38)
=> BL-7368 Bloom Player screen tap mods

src/bloom-player-core.tsx
Video and audio are loaded as needed. Images are loaded in the background, with no limits at this point (e.g. not just one page ahead).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/42)
=> BL-7423 Load images progressively

package.json, src/narration.ts
This fix allows audio that is not in the vernacular to play.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/47)
=> Apply BL-6839 fix to bloom-player (BL-7175)

package.json, src/bloom-player.less
The missing keywords appear to be valid and critically needed.  I tested
this in both the stand-alone browser view and in the Bloom publish
preview.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/58)
=> Fix Andika New Basic for Bold and Italic (BL-7553)

src/bloom-player.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/63)
=> Correctly hide app bar based on its height (BL-7607)

src/bloom-player-core.tsx, src/bloom-player.less, webpack.common.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/71)
=> Get rid of vestiges of slick by using material navigations buttons (BL-7480)

src/bloom-player-controls.tsx, src/bloom-player-core.tsx, src/bloom-player.less, src/controlBar.tsx, src/langData.ts, src/languageMenu.tsx, src/stories/index.tsx
* language data provided by callback from
bloom-player-core to bloom-player-controls
* LanguageMenu sends new selected language
up to BloomPlayerControls where the language
data is stored and change is sent down to
BloomPlayerCore via the activeLanguageCode prop
* for now we are getting language iso codes and
display names from 'language-display-names'
field of meta.json
* fix bug in fixRelativeUrls()
* this is a second try at a PR; this one rebuilds the Swiper
when the language changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/70)
=> BL-7610 Add language chooser

.gitignore, package.json, src/activities/loadDynamically.js, webpack.common.js, yarn.lock
The babel-based one wasn't actually working.
Also updates and expands the list of browsers we want bloom-player to support
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/80)
=> BL-7763 change to a different polyfill for dynamic import

src/bloom-player.less
* Prettier changed spacing
* "Real" changes are line 19 and 22-24, margin-left
rules in both files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/86)
=> BL-7758 Keep paging handles from quiz btns

src/langData.ts
* case: no "language-display-names" field present
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/88)
=> BL-7811 Handle book with older meta.json

src/animation.ts, src/bloom-player-core.tsx, src/narration.ts
* Add delay for non-audio page if we're doing
autoadvance
* Get this working by cancelling timers
* Tested in Desktop preview and BR2.0
* Doesn't work in Storybook
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/101)
=> BL-7633 Reconnect autoplay

src/bloom-player-core.tsx
Three related goals of this PR:
1) Fix bug where editables marked as Local Language Only ("V") were not displaying right after switching to a different language using the language chooser.
2) Change updateDivVisibility...() logic to be largely state-independent instead of heavily state-dependent.
3) Change updateDivVisbiility...() logic to follow Bloom Desktop's visibility system as closely as possible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/103)
=> Change updateDivVisibility to follow BloomDesktop model of visibility (BL-8093)

README.md, package.json, src/activities/ActivityContext.ts, src/bloomplayer.htm, webpack-config-prod.js, webpack.common.js, yarn.lock
All asset files are now generated and used with hashed names so they can be cached safely by clients.
bloom-player is generated with a hashed script tag for the main JS file.
Removed several obsolete (at least for now) output files. (Turns out we never needed to ship the tsv file, it was being inlined.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/106)
=> Reduce and hash assets bloom-player needs

src/narration.test.ts, src/narrationUtils.ts
* We decided that TGs with no tabindex should be sorted
to the end, if there are others that have tabindex
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/118)
=> BL-7883/8340 Adjust sort algorithm

src/bloom-player-core.tsx
* Bloom desktop puts Leveled/Decodable reader classes
on the body element of the html. These weren't getting
passed on to BP. Now we put them on the
div.bloomPlayer-page so they are available inside of the
scoped CSS rules.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/121)
=> Transmit body classes to BP

src/autonyms.ts, src/langData.ts
* don't ever show 'unknown'
* handle 'zh-CN' gracefully
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/127)
=> BL-8268 Language Picker

src/bloom-player-core.tsx
This also fixes BL-8806, another manifestation of the same bug.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/139)
=> Ensure navigation buttons on pages with draggable activities (BL-8680)

package.json
Backslashes are just wrong for "cross-platform" tools.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/140)
=> Get the tobloomreader and other to targets working on Linux (20200819)

README.md, index-for-developing.html, src/bloom-player-controls.tsx, src/controlBar.tsx, src/stories/index.tsx
This change implies fixes to BloomReader (where full-screen doesn't
make sense) and Bloom Library (which has its own full-screen button, but
maybe could do without now).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/142)
=> Allow bloom-player control over showing itself full-screen (BL-8834)

src/bloom-player-controls.tsx, src/bloom-player.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/161)
=> Improving the positioning of the big Play button (BL-9075)

src/bloom-player-controls.tsx, src/bloom-player-core.tsx, src/bloom-player.less
Also cleans up some naming and abuse of react state
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/167)
=> Improvements to talking book accessibility for blind (BL-9075 pt 2)

src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/175)
=> Ignore xmatter for overlay scrollbar (BL-9249)

src/bloom-player.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/176)
=> Fix the width of the content in IOS 10-12 (BL-9296)

src/bloom-player-core.tsx, src/bloom-player.less
Inserts the button inline and hides the video element.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/186)
=> One workaround for Chrome hiding Replay button (BL-9304)

src/bloom-player.less
I tried this in storybook in both firefox 60 and chromium 88.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/190)
=> Fix display bug with activity pages in publish preview (BL-8900)

src/bloom-player.less
Reverts BloomBooks/bloom-player#190
We decided this was not a good fix due to side-effects when sliding pages instead of clicking on the next/previous buttons.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/191)
=> Revert "Fix display bug with activity pages in publish preview (BL-8900)"

src/externalContext.ts
In order for the bloom-player library to work in RAB apps for iOS, there is a slightly different method of implementing sendMessageToHost for the iOS WKWebView.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/196)
=> iOS: Use webkit.messageHandlers for sendMessageToHost

src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/204)
=> Recognize unsplit image description textbox mode recordings (BL-9750)

src/bloom-player-core.tsx
Also ensure that music from previous page pauses when a new page starts
off with a video.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/212)
=> Ensure music pauses when user clicks on the pause button (BL-9967)

src/bloom-player-core.tsx
bloom-translationGroups that are vertically centered or aligned bottom use display:flex. When they overflow, the browser tries to compress the text, sometimes to the point of overlapping and being unreadable. If we use flex-shrink:0 to prevent this, nicescroll fails to provide scrolling.  This PR simply turns this off for overflowing blocks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/216)
=> Fix problems with overflowing boxes using flex (BL-10053)

src/activities/legacyQuizHandling/old-questions.ts
Previously, it was using an outdated method of localization
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/220)
=> Update localization for Legacy Quizzes (BL-9795)

src/bloom-player-core.tsx
Note: the diff is confusing. Think of what happened as that a block of text that was previously used to initialize combinedStyles in assembleStyleSheets() got moved to a new method that makes the andika style sheet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/243)
=> Move @font-face rules for Andika out of scoped style (BL-10815)

src/animation.ts
...to the div that actually has the background image, where it's less likely to sneak through than when its on the wrapper.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/261)
=> Move the white background behind animation down a level (BL-11094)

src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/320)
=> Set correct visibility when initial lang is not default (BL-13318)

src/bloom-player-core.tsx, src/dragActivityRuntime.ts
This also brings dragActivityRuntime.ts up to date with Bloom Desktop.
The only change to that file, I believe, that hasn't already been reviewed there is making playSoundOf exported and adding preventDefault/stopPropagation. (Also the only change we actually need here until bloom games go live, but I prefer to keep the files in sync.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/321)
=> Support data-sound and prevent video click toggling app bar

src/bloom-player-ui.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/324)
=> fix: Hide native play/pause button for videos on Android (BL-12299)

src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/333)
=> Prevent swiping pages when clicking on video buttons (BL-14021)

src/bloom-player-core.tsx
This change allow simple anchor element href values to work without changing them to data-href values.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/337)
=> feat: Send bloomnav links to the host window to handle (BL-13882)

src/narration.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/338)
=> fix: Add background color for video error messages (BL-13906)

src/dragActivityRuntime.ts
The only non-formatting change is the call to doShowAnswersInTargets which changes "true" to "!inPlayer" (plus the preceding line, of course) around line 297.  I don't why VSCode changed so much formatting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/340)
=> fix: Prevent showing game answers when sliding pages (BL-14064)

src/activities/dragActivities/DragToDestination.ts, src/dragActivityRuntime.ts, src/narration.ts
Also clean up playAllVideos in narration.ts a bit (which is now used only by Bloom Desktop)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/346)
=> fix: Get games to not play embedded videos twice (20241202)

src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/350)
=> fix: Restore "working" as a URL alias in BloomDesktop preview (20250109)

src/bloom-player-controls.tsx, src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/351)
=> fix: adjust page scaling when following link to book (BL-14198)

src/bloom-player-core.tsx
I simplified this logic drastically. If the old logic has a purpose, it should be added to preprocessUrl() with comments. As far as I can see, state.bookUrl always has a leading slash, and in that case the logic I've removed never assigns this.sourceUrl to be anything other than newSourceUrl.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/352)
=> fix: prevent a possible render problem

src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/355)
=> fix: Restore handling of missing URL (BL-14269)

src/dragActivityRuntime.ts
Not sure how this used to work.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/361)
=> fix: a selector without closing bracket

src/shared/dragActivityRuntime.ts
This ensures the proper default font is chosen for the words.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/379)
=> fix: Add lang attribute to .drag-item-order-word elements (BL-14885)
