- src/bloom-player-controls.tsx
- src/bloom-player-core.tsx
- src/bloom-player.less
- src/narration.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/2)
> Tweak size algorithm for mixed-orientation pages in slider

- .vscode/launch.json
- jest.config.js
- package.json
- src/babel.config.js
- src/bloom-player-core.tsx
- src/jest.config.js
- src/old-questions.test.ts
- src/old-questions.ts
- src/simpleComprehensionQuiz.js
- yarn.lock
Also bumps version number so we can push to npm
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/4)
> Add handling of questions.json (old-style comprehension questions)

- src/bloom-player-controls.tsx
- src/bloom-player-core.tsx
- src/externalContext.ts
- src/video.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/7)
> BL-7163 Get video working

- package.json
- src/video.ts
* unless unpausing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/8)
> BL-6985 Don't start video for 1 second, bump to 0.6.7

- package.json
- src/bloom-player-core.tsx
Preventing yellow boxes in Bloom
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/9)
> BL-7176 Use DomParser to parse book HTML

- src/bloom-player.less
- src/narration.ts
Supports sentence-by-sentence highlighting of an audio file corresponding to a whole text box
(Confer https://github.com/BloomBooks/BloomDesktop/pull/3158)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/5)
> Narration sentence highlighting (BL-7024)

- src/narration.ts
Also, seems Prettier was applied.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/10)
> Fix TSLint errors in narration

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/11)
> Bump version num to 0.7.0 because of new narration functionality/format

- package.json
- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/12)
> BL-7186 Accept full htm file urls and handle %2f

- src/legacyQuizHandling/old-questions.test.ts
- src/legacyQuizHandling/old-questions.ts
Unfortunately diff contains a lot of changes from pretty-printing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/15)
> BL-7019 handle multiple question pages and json from quiz pages

- package.json
- src/legacyQuizHandling/simpleComprehensionQuiz.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/16)
> Fix window.BloomPlayer is not defined js error (BL-7214)

- package.json
- src/bloom-player-controls.tsx
- src/bloom-player.less
- src/bloomPlayerTheme.ts
- src/bloomplayer.htm
- src/controlBar.tsx
- src/externalContext.ts
- webpack-config-prod.js
- yarn.lock
- with back button and play/pause
- also: got rid of black bar at bottom of page
- center player when too narrow to fill window
- add material design and theme
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/18)
> BL-7211 Add app bar

- package.json
- src/controlBar.tsx
- src/externalContext.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/20)
> BL-7274 Hide features the parent does not support

- .gitignore
- package.json
- src/bloom-player-core.tsx
- src/bloomplayer.htm
- src/externalContext.ts
- src/l10n/i18n.json
- src/l10n/localizationManager.test.ts
- src/l10n/localizationManager.ts
- src/l10n/localizationUtils.test.ts
- src/l10n/localizationUtils.ts
- src/legacyQuizHandling/old-questions.test.ts
- src/legacyQuizHandling/old-questions.ts
- updateFiles.bat
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/13)
> Add a header to the new comprehension quiz (BL-7191)

- package.json
- src/l10n/localizationManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/21)
> Fix bloom-player in FF45 and Bloom preview (BL-7191)

- package.json
- src/bloom-player-core.tsx
- src/externalContext.ts
- src/narration.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/22)
> BL-7256 provide data to reader for pages-read, book-opened

- package.json
- src/bloom-player-core.tsx
- src/externalContext.ts
- src/narration.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/23)
> BL-7317 Don't report a page as having audio if we are paused

- README.md
- package.json
- src/bloom-player-core.tsx
- src/bloomplayer.htm
- src/controlBar.tsx
- src/narration.ts
* moved controlBar colors to material-ui theme
* replaced deprecated SFC
* enabled sentence highlighting on (uncounted)
page replay
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/24)
> BL-7306 Fix Sentence Highlighting on replay

- src/bloom-player.less
- src/bloomPlayerTheme.ts
- src/controlBar.tsx
* make bloom primary color gray, secondary red
* use provided theme correctly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/25)
> Work on using the material-ui theme file

- package.json
- src/bloom-player-core.tsx
* version assumes PR#26 goes in before this
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/27)
> BL-7334 Don't count xmatter pages as audio read

- package.json
- src/bloom-player-core.tsx
- src/narration.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/26)
> BL-7306 Fix changing page while paused bug

- package.json
- src/bloom-player-core.tsx
- src/externalContext.ts
- src/narration.ts
- src/video.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/28)
> BL-7255 report duration of audio and video played

- package.json
- src/legacyQuizHandling/old-questions.test.ts
- src/legacyQuizHandling/old-questions.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/29)
> BL-7019 Make quiz pages generated from json be numbered

- README.md
- build/s3publish.proj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/30)
> BL-7332 improve ReadMe and add S3 publishing

- build/s3publish.proj
- package.json
- src/bloom-player-core.tsx
- src/legacyQuizHandling/Special.css
- src/legacyQuizHandling/readme.txt
- updateFiles.bat
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/32)
> Produce and use special.css for legacy quiz pages

- src/bloom-player-controls.tsx
- src/bloom-player.less
- src/narration.ts
Yellow border for image when playing image description;
buttons outside phone when there is room in portrait mode
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/34)
> BL-7411 Tweaks for Bloom Library

- package.json
- src/controlBar.tsx
- src/externalContext.ts
Note: I have no idea how the back button worked and was red in BR-RN without these changes, but they are definitely needed in the web page context.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/35)
> BL-7411 Support using back button in BL

- package.json
- src/narration.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/36)
> Don't highlight image when doing playback of TOP text

- package.json
- src/bloom-player.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/37)
> BL-7442 Talking book highlight messes up book titles 

- src/bloom-player-core.tsx
- src/legacyQuizHandling/simpleComprehensionQuiz.js
Also makes BP use its own version of simpleComprehensionQuiz.js exclusively
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/39)
> BL-7462 Play sound once (attach comp. question. listener just once)

- package.json
- src/bloom-player-controls.tsx
- src/bloom-player-core.tsx
- src/bloom-player-root.ts
- src/bloom-player.less
- src/externalContext.ts
- src/narration.ts
- src/video.ts
- updateFiles.bat
...and various other changes connected with using in BloomReader, such as an alternative way to communicate with the outer tool.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/40)
> BL-7443 move more analytics handling into player

- package.json
- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/44)
> BL-7480 Make a shorter swipe enough to flip the page

- package.json
- src/animation.ts
- src/bloom-player.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/41)
> Fix bloom-player animation for picture-only pages (BL-7452)

- package.json
- src/bloom-player.less
* bump version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/46)
> BL-7162 Set overflowing block to scroll

- src/bloom-player.less
- src/bloomPlayerTheme.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/45)
> BL-7481 make book background use title bar color

- package.json
- src/bloom-player-controls.tsx
- src/bloom-player-core.tsx
- src/music.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/50)
> Add background music handling to bloom-player (BL-7493)

- package.json
- src/bloom-player-controls.tsx
- src/bloom-player.less
BL-7382 also has a Bloom Editor aspect, but these PRs are independent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/48)
> BL-7382 Make nav buttons work in landscape and have 3 modes

- package.json
- src/music.ts
Also fix volume setting to be more accurate for background music.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/51)
> Fix background music to continue as desired on adjacent pages (BL-7493)

- package.json
- src/bloom-player.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/52)
> BL-7162 Part 2... the fudges

- src/narration.ts
Applying a change in LegacyBloomPlayer to here as well for consistency and robustness
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/53)
> Talking Book: Add fallback algo if currentTime field not set (BL-7537)

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/54)
> Bump version number to 0.9.37

- CHANGELOG.md
- README.md
- index-for-developing.html
- package.json
- src/bloom-player-controls.tsx
- src/externalContext.ts
Added `initiallyShowAppBar`, `allowToggleAppBar`, and `showBackButton` url params. See readme for details.
Removed the "capabilities" message exchange.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/55)
> BL-7544 Simplify Client Setup

- src/legacyQuizHandling/simpleComprehensionQuiz.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/56)
> Fix saving of quiz answers (BL-7532)

- src/bloom-player-core.tsx
- src/stories/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/61)
> Stop multimedia when leaving the book (BL-7580)

- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/62)
> BL-7425 Work around defective bloomd xmatter page markup

- src/bloom-player-controls.tsx
- src/externalContext.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/64)
> Show/hide the parent (Android) navigation bar along with the app bar (BL-7516)

- src/bloom-player-controls.tsx
- src/externalContext.ts
* required for BR PR
* in case BR (or some other app) is listening
* reports if book can rotate and if book is landscape
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/65)
> BL-7536 Report book properties

- src/video.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/66)
> BL-7535 report failure to play a video (at least to console)

- src/bloom-player-controls.tsx
- src/externalContext.ts
- src/stories/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/68)
> Allow an external controller (Bloom Reader) to manipulate pause/play (BL-7580)

- package.json
- src/bloom-player-controls.tsx
Also added npm scripts for copying to BloomDesktop
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/72)
> Fix storybook book switching (BL-7480)

- src/bloom-player-core.tsx
- src/externalContext.ts
- src/narration.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/73)
> Make Home and End keys work no matter where the focus is (BL-7480)

- src/bloom-player-controls.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/74)
> BL-7610 Fix bug in Lg chooser code

- src/langData.ts
* helps it run in BR better
* finds a fallback name for the first language from
book's dataDiv if necessary
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/75)
> BL-7610 Make Lg Chooser more robust

- package.json
- src/autonyms.ts
- src/bloom-player-core.tsx
- src/iso639-autonyms.tsv
- src/langData.ts
- src/rawLoader.d.ts
- webpack.common.js
- yarn.lock
* AutonymHandler loads and retrieves data
* Fix visibility bug in bi-/tri-lingual books
* Used better business logic for menu items
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/76)
> BL-7610 Add autonym file

- src/bloom-player-core.tsx
- src/langData.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/78)
> Bug fix to LangData array creation

- src/langData.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/79)
> BL-7610 Ignore data-book divs in determining audio

- src/bloom-player-core.tsx
- src/stories/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/83)
> Fix fonts with spaces or parentheses in the file name (BL-7779)

- src/langData.ts
* Now works for Record Whole Textbox mode too
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/85)
> BL-7797 Update audio detection for Lg Menu

- src/bloom-player.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/87)
> BL-7663 Center swiper buttons vertically

- src/langData.ts
Shoulda looked a little further.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/89)
> BL-7811 Fix another bug

- src/bloom-player.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/90)
> BL-7517 Retrofit old books to not show yellow box

- src/activities/legacyQuizHandling/Special.css
- src/bloom-player.less
* BP part is mostly copying from Desktop for now
* Eventually we want all this code to live in BP
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/92)
> BL-7758 Leave room for quiz boxes - try 2

- src/bloom-player-core.tsx
- src/bloom-player.less
- src/stories/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/94)
> Improve reporting of problems loading local files (BL-7813)

- src/activities/ActivityContext.ts
- src/activities/activityManager.ts
- src/activities/domActivities/SimpleCheckboxQuiz.ts
- src/bloom-player-core.tsx
- src/page-api.ts
* Swiper optimization really speeded up page turning,
but it messed up analytics reporting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/93)
> BL-7885 Get BR to report accurate quiz stats

- src/bloom-player.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/95)
> Hide overflow in bubbles (BL-7911)

- src/bloom-player.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/97)
> Fix radio controls in bloom-player language picker (BL-7960)

- src/bloom-player.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/98)
> Try another approach for detecting touchscreen in css (BL-7987)

- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/99)
> Change analytics to count each page in a book only once (BL-7888)

- src/langData.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/100)
> Don't rely on language-display-names order to get language 1 (BL-8008)

- src/bloom-player.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/102)
> BL-8076 Get BP to stop cutting off bubble text

- .editorconfig
- .gitattributes
- src/autonyms.ts
- src/iso639-autonyms.tsv
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/105)
> Update and reduce file size of iso639-autonyms.tsv

- src/animation.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/107)
> Fix animation for images with a ) in the file name (BL-8207)

- src/animation.ts
- src/bloom-player-core.tsx
- src/stories/index.tsx
- src/utilities/domHelper.test.ts
- src/utilities/domHelper.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/109)
> Improve finding image url from style attribute (BL-8207)

- src/animation.ts
- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/108)
> Don't play animation if not a "motion book" (BL-8026)

- src/bloom-player-controls.tsx
- src/bloom-player-core.tsx
- src/stories/index.tsx
Reviewed/helped by JH
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/111)
> Add ability to set initial language code via a url parameter (BL-8289)

- README.md
- index-for-developing.html
- src/bloom-player-controls.tsx
And add to README.md.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/112)
> Actually hook up the url parameter (BL-8289)

- src/bloom-player-controls.tsx
- src/bloom-player-core.tsx
- src/stories/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/113)
> Add useOriginalPageSize param (BL-8296)

- src/bloom-player.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/114)
> Reduce A5 margins while keeping marginBox size fixed

- src/narration.test.ts
- src/narration.ts
- src/narrationUtils.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/115)
> Play audio partially ordered by tagindex of translation group (BL-8340)

- src/langData.ts
- src/languageMenu.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/116)
> Handle an explicit request to show book in its first language (BL-8375)

- src/bloom-player-core.tsx
- src/stories/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/120)
> Always show comics in original page size (BL-8438)

- src/bloom-player-core.tsx
- src/stories/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/122)
> Fix glitch preventing page buttons showing on activity pages

- src/bloom-player-controls.tsx
- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/123)
> Improve control of outside buttons

- src/bloom-player-core.tsx
- src/bookInfo.test.ts
- src/bookInfo.ts
- src/bookInteraction.test.ts
- src/bookInteraction.ts
- src/narration.test.ts
- src/test/testHelper.ts
Also add a few new fields for analytics
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/125)
> Refactor core to pull out BookInfo and BookInteraction (BL-8474)

- src/controlBar.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/128)
> BL-8457 Hide BPlayer Lg Menu if no choice

- src/bloom-player-controls.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/129)
> BL-8458 Center bloom player vertically

- index-for-developing.html
- src/bloom-player-controls.tsx
* add centerVertically param that will be used by BR and
Desktop BR preview, but not Read on the web
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/130)
> BL-8458 center vertically mod

- index-for-developing.html
- src/bloom-player-controls.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/131)
> BL-8458 Center vertically - switch default to true

- src/bloom-player-controls.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/132)
> BL-8458 center vert - found 2 bugs

- src/bloom-player-controls.tsx
- src/controlBar.tsx
- src/externalContext.ts
- src/stories/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/134)
> Allows host to request extra toolbar buttons in player

- src/narration.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/135)
> Stop narration from previous page when starting new page (BL-8678)

- src/controlBar.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/137)
> Back button looks like 'more' when embedded

- src/narration.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/138)
> Prevent previous page's timeouts from affecting current page (BL-8797)

- src/bloom-player-core.tsx
- src/narration.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/145)
> Fix landscape books to play initial audio (BL-8887)

- src/bloom-player-core.tsx
- src/narration.ts
- src/narrationUtils.ts
There's also a very similar PR for BloomDesktop
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/144)
> Talking Book: Scroll highlighted element into view (BL-8860)

- src/bloom-player-core.tsx
- src/narration.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/147)
> Fix bug where pause/play causes highlighting to stop working (BL-8906)

- README.md
- index-for-developing.html
- src/Environment.ts
- src/bloomPlayerAnalytics.tsx
- src/bookInfo.ts
- src/externalContext.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/146)
> Send analytics directly from bloom-player (BL-8874)

- src/bloom-player-controls.tsx
- src/bookInfo.ts
- src/utilities/urlUtils.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/151)
> Fix failing test by moving url utilities to urlUtils.ts (BL-8874)

- src/bloom-player.less
- src/sample-canvas-activity/index.htm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/152)
> Work around Chrome-85 bug hiding next page button (BL-8936)

- src/bloom-player-controls.tsx
- src/bloom-player.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/153)
> Another try at working around the Chrome85 bug (BL-8874)

- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/154)
> Focus the next-page button on loading document (BL-8980)

- src/bloom-player-controls.tsx
- src/bloom-player-core.tsx
- src/stories/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/156)
> BloomPlayer now expects URLs to be properly encoded (BL-9041)

- src/bloom-player-controls.tsx
- src/bloom-player-core.tsx
- src/narration.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/157)
> Set state to paused when initial playback fails (BL-8864)

- src/bloom-player-controls.tsx
- src/bloom-player-core.tsx
- src/bloom-player.less
- src/controlBar.tsx
- src/l10n/i18n.json
- src/l10n/localizationManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/158)
> Make BP more accessible, especially for vision-impaired (BL-9075)

- src/music.ts
- src/narration.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/160)
> Avoid big 'play' button trying to play non-existent music (BL-9075)

- index-for-developing.html
- src/bloom-player-core.tsx
- src/music.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/162)
> Improve music handling, especially showing/hiding play/pause (BL-7703)

- src/narration.ts
- src/stories/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/163)
> Improve reliability of audio playback

- src/controlBar.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/164)
> Possible fix for IOS problems (BL-9144)

- src/bloom-player-controls.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/165)
> Prevent another error that just might be messing up IOS (BL-9144)

- src/bloom-player-core.tsx
- src/stories/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/166)
> Fix currentPage after reloading for new language (BL-8912)

- src/bloom-player-controls.tsx
- src/bloom-player-core.tsx
- src/bloom-player.less
- src/narration.ts
- src/stories/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/168)
> Get Bloom Player working on IOS (with various other cleanup and optimization)

- package.json
- src/bloom-player-core.tsx
- src/bloom-player.less
- src/overlayScrollbars-bloom.css
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/169)
> Add OverlayScrollbars to handle overflowing text boxes instead (BL-9249)

- src/bloom-player-core.tsx
- src/stories/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/170)
> Hide national language title when alternative lang chosen (BL-9256)

- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/171)
> Hide unwanted national title on title page also (BL-9256)

- src/bloom-player-controls.tsx
- src/bloom-player-core.tsx
- src/bloom-player.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/172)
> Don't show the player until it is scaled (BL-9301)

- index-for-developing.html
- src/bloom-player-controls.tsx
- src/bloom-player-core.tsx
* 2 commits, 1st is Prettier and a small dev html fix, 2nd is regression fix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/174)
> BL-9307 Fix a regression in div visibility when fed a 'lang' parameter

- src/bloom-player-core.tsx
- src/narration.ts
- src/video.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/178)
> Play video before audio and animation (BL-9302)

- package.json
- src/bloom-player-core.tsx
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/181)
> Change nicescroll package to official one on NPM

- src/bloom-player-core.tsx
- src/music.ts
- src/narration.ts
- src/video.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/182)
> Stop narration when changing pages (BL-9302)

- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/183)
> Tweak niceScroll scrollbar styling (BL-9397)

- src/bloom-player-controls.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/184)
> Fix shrunken preview of BloomPub books inside Bloom (BL-9395)

- src/bloom-player-core.tsx
- src/video.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/185)
> Add button to replay video (BL-9304)

- index-for-developing.html
- src/utilities/osUtils.ts
- src/video.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/187)
> Allow videos w/audio to be playable on iOS/MacOS (BL-9383)

- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/188)
> The fix seems to be needed also on Safari (BL-9304)

- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/192)
> Trying again, hiding video on all platforms BL-9304

- package.json
- src/bloom-player-core.tsx
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/193)
> Fix odd layout bug caused by scoped styles (BL-9504)

- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/194)
> Ensure state.styleRules does not get modified after initial pass (BL-9504)

- src/bloom-player-controls.tsx
- src/bloom-player-core.tsx
- src/bloom-player.less
- src/bloomPlayerTheme.ts
- src/controlBar.tsx
- src/narration.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/198)
> BL-8993 highlight image description icon

- index-for-developing.html
- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/202)
> Fix TextBox mode talking books with image descriptions (BL-9750)

- webpack.common.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/203)
> Fix some broken loops for l10n file fetching (BL-9134)

- src/activities/domActivities/SimpleCheckboxQuiz.ts
* some needed code was stripped out of the simplified
version for B-P
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/214)
> BL-10037 Make Comp Question answers visible

- src/bloom-player-core.tsx
- src/stories/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/215)
> Prevent narration playing from previous pages (BL-10039)

- src/bloom-player-controls.tsx
- src/bloom-player-core.tsx
- src/l10n/localizationManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/221)
> Prefer localizing into the browser language first (BL-9796)

- testBooks/test-widget-iframe-messages/activities/ORCoast/rlprez.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/224)
> BL-9871 update/simplify js for pasting into buttons

- src/bloom-player-core.tsx
- src/externalContext.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/225)
> Fix crash in Chrome on iOS (BL-10216)

- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/226)
> Don't use niceScroll unless we need it (BL-10217)

- package.json
- src/bloom-player-core.tsx
- src/bloomPlayerAnalytics.tsx
- src/bookInteraction.ts
- src/externalContext.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/227)
> Add readDuration property to pages read event (BL-10230)

- index-for-developing.html
- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/229)
> Another try at using niceScroll only when we need it (BL-10217)

- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/231)
> BL-9743 Stop Replay btn toggling BP toolbar in Mobile env.

- README.md
- src/externalContext.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/230)
> Allow blorg to report readDuration (BL-10230)

- src/bloom-player.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/233)
> Workaround for scrollbar sometimes missing (BL-10217)

- src/bloom-player-core.tsx
- src/stories/index.tsx
- testBooks/sign-language-with-talking-book/sign-language-with-talking-book.htm
Including links to other pages in this book
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/238)
> Handle URLs in book pages (BL-10374)

- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/239)
> Prevent parent listeners on in-page hyperlinks (BL-10402)

- .vscode/extensions.json
- package.json
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/241)
> Upgrade to node LTS & latest eslint

- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/246)
> A better way to figure whether things overflow

- jest.config.js
- package.json
- src/jest.config.js
- yarn.lock
Jest tests were failing to compile, and there were 4 places with competing jest directives.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/247)
> Fix up jest

- src/stories/index.tsx
- src/video.ts
* add offending book to storybook
* fix video play when no longer on the right page
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/249)
> BL-9740 Stop audio of video on next page

- src/bloom-player-core.tsx
- src/bloom-player.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/250)
> Allow badly-overflowing bubbles to scroll (BL-10536)

- src/bloom-player.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/251)
> Further tweak to scroll bar in bubble (BL-10536)

- src/bloom-player-controls.tsx
- src/bloom-player-core.tsx
- src/controlBar.tsx
- src/music.ts
- src/narration.ts
- src/stories/index.tsx
- src/videoRecordingSupport.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/255)
> Support Bloom Editor recording book as video (BL-10991)

- src/utilities/urlUtils.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/258)
> Boolean Query string parameters are no longer case sensitive

- src/videoRecordingSupport.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/259)
> Don't throw on pause after sound log sent (BL-11036)

- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/260)
> Fade rather than slide when in autoplay mode (BL-11052)

- src/animation.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/262)
> Allow motion book animation with all page sizes (BL-11095)

- src/animation.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/264)
> Make the animation continue into page fade (BL-11100)

- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/266)
> Adjust page orientation after switching autoplay mode (BL-11090)

- src/bloom-player-core.tsx
- src/bookInfo.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/265)
> Have BP handle .distribution analytics info (BL-8898)

- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/267)
> Make NiceScroll capture the pointer for click in thumb (BL-11134)

- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/268)
> Only clean up niceScrolls when changing pages (BL-11070)

- src/bloom-player-controls.tsx
- src/bloom-player-core.tsx
- src/stories/index.tsx
Draft until corresponding Bloom editor PR is approved. Should be merged together since this one will cause Preview to autoplay immediately without the BE change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/269)
> Support for autoplay of specified range

- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/270)
> Hide language name and topic on cover when not displaying default language (BL-11133)

- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/271)
> Better hide National1 title when alternate L1 chosen (BL-11245)

- src/bloomPlayerAnalytics.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/275)
> Use production analytics files rather than next.blorg (BL-11372)

- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/277)
> Tweak scroll algorithm to allow for rounding errors (BL-11364)

- src/activities/domActivities/SimpleCheckboxQuiz.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/280)
> Remove no longer needed logging statements

- src/bloom-player.less
- src/narration.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/281)
> Disable highlight of multiple spaces (BL-11485)

- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/283)
> Fix changing language on an activity page (BL-11449)

- src/music.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/284)
> No music on pages following explicit no-music (BL-11333)

- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/285)
> Prevent double page advance (BL-11368)

- src/narration.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/286)
> Avoid horizontal scrolling to show almost-visible text (BL-11038)

- src/bloom-player-core.tsx
- src/narration.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/287)
> Fix multilingual narration for books when changing language (BL-11449)

- src/narration.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/288)
> Work around Firefox 60 bug/feature to prevent unwanted narration (BL-11449)

- src/narration.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/289)
> Fix scrolling bubble to show text being read (BL-11038)

- src/narration.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/290)
> Fix check for FF60 (BL-11449)

- src/activities/activityManager.ts
- src/activities/domActivities/SimpleCheckboxQuiz.ts
- src/activities/domActivities/SimpleDomChoice.ts
- src/activities/iframeActivity.ts
- src/bloom-player-core.tsx
- src/narration.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/291)
> Set up activities before their first display (BL-11449)

- package.json
- src/stories/playerInteractionTests.tsx
* used better testing methods on existing tests
* added a book w/an activity (which is hard to test with this)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-player/297)
> Upgrade some testing

- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/299)
> Support adjusting comic bubbles by language (BL-10391)

- src/bloom-player-controls.tsx
- src/bloom-player-core.tsx
- src/languageMenu.tsx
Also updates the visibility of the PlayPause button
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/301)
> Stop old audio playback when language changed (BL-10511)

- src/bloom-player-controls.tsx
- src/bloom-player-core.tsx
- src/bloom-player.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/303)
> Another attempt at handling RTL books (BL-8063)

- src/langData.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/304)
> Prevent spurious claims of audio data in extra language (BL-12023)

- src/bloom-player.less
2nd of 2 PRs. The other in Bloom Editor
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/305)
> [5.5] BL-12675 Keep white space in Title during audio

- src/bloom-player.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/307)
> BL-13053 fix talking book highlighting color customization

- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/308)
> Simplify how BP decides what fields should be visible (BL-13042)

- src/bloom-player-controls.tsx
- src/bloom-player-core.tsx
- src/bloom-player.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/309)
> Remove unused and broken parameter: showContextPages

- .gitignore
- .vscode/settings.json
- src/bloom-player-content.less
- src/bloom-player-controls.tsx
- src/bloom-player-core.tsx
- src/bloom-player-pre-appearance-system-book.less
- src/bloom-player-ui.less
- src/bloomPlayerTheme.ts
- src/bookInfo.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/310)
> Clean up .less files; allow removing book-display rules (BL-13311)

- src/bloom-player-pre-appearance-system-book.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/311)
> Fix two problems with non-appearance books (BL-13311)

- src/bloom-player-content.less
- src/bloomPlayerTheme.ts
- src/controlBar.tsx
- src/narration.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/312)
> Fixes for audio highlighting (BL-13428)

- src/narration.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/313)
> Handle zero-width spaces for audio highlighting (BL-13428)

- src/bloom-player-ui.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/314)
> Reinstate rule to hide outline (BL-13590)

- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/315)
> fix: Handle language switching in simple activities

- src/bloom-player-core.tsx
- src/bloom-player-ui.less
- src/dragActivityRuntime.ts
- src/narration.ts
- src/video.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/317)
> fix: Play all videos on the page (BL-13705)

- src/video.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/318)
> BL-13824 show video element controls

- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/322)
> Ensure replay buttons work reliably (follow up BL-12299)

- src/narration.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/323)
> fix: Stop audio in progress immediately when changing pages (BL-13905)

- src/bloom-player-core.tsx
- src/l10n/_locales/en/messages.json
- src/narration.ts
- src/video.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/325)
> feat: display message when browser can't play video (BL-13906)

- src/l10n/_locales/en/messages.json
- src/narration.ts
- src/video.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/326)
> fix: Remove circular dependency which caused test failures (BL-13906)

- .husky/commit-msg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/328)
> chore: Tighten up the check in the commit message hook (20240925)

- src/bloom-player-core.tsx
- testBooks/Testing Away Again/index.htm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/327)
> feat: Make images and text follow data-href when touched (BL-13879)

- src/bloom-player-core.tsx
- src/bloom-player-ui.less
- src/pauseIcon.ts
- src/playIcon.ts
- src/replayIcon.ts
- src/video.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/329)
> Make our own video controls (BL-13957)

- src/video.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/330)
> fix: Pause for touch on video (BL-13957)

- src/activities/domActivities/SimpleCheckboxQuiz.css
- src/activities/domActivities/SimpleCheckboxQuiz.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/331)
> fix: Prevent clicks on choices being treated as drags (BL-13999)

- src/activities/ActivityContext.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/334)
> fix: Don't keep adding audio players for activity sounds (BL-14017)

- src/narration.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/336)
> fix: Make video error message visible again (BL-13906)

- src/bloom-player-controls.tsx
- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/335)
> fix: Adjust the nicescroll position as the window changes size (BL-13796)

- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/339)
> fix: Prevent scrolling from also swiping (BL-14079)

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/342)
> chore: Update README.md for vite and unit tests (20241121)

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/343)
> chore: Tweak unit test wording in README.md (20241121)

- .storybook/main.ts
- src/bloom-player-core.tsx
- src/stories/navigation.stories.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/354)
> fix: Use URLs relative to the book's root

- src/animation.ts
- src/bloom-player-core.tsx
- src/narration.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/356)
> fix: for black screens, double-page turns in motion books (BL-13905)

- src/narration.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/358)
> fix: Prevent black screen in BloomPUB Viewer (BL-14320)

- package.json
- src/bloom-player-core.tsx
- src/dragActivityRuntime.ts
- src/event.ts
- src/narration.ts
- src/scrolling.ts
The major work was merging the changes that have been made to these four files differently in bloom-player and BloomDesktop.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/357)
> feat: Export shared source files in bloom-player package (BL-14008)

- README.md
- package.json
- src/bloom-player-controls.tsx
- src/bloom-player-version-control.tsx
- vite.config.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/359)
> chore: BL-14342 Display version and build date

- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/360)
> fix: abort narration changing pages (BL-14341)

- src/animation.ts
- src/bloom-player-content.less
- src/bloom-player-core.tsx
- src/shared/dragActivityRuntime.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/363)
> fix: Update for new bloom-canvas class for holding images

- .vscode/settings.json
- src/shared/dragActivityRuntime.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/364)
> fix: Make retry button reset draggable piece positions (BL-14482)

- src/shared/dragActivityRuntime.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/367)
> fix: Handle dragging games properly on touch devices (BL-14502)

- src/shared/dragActivityRuntime.ts
This is the bloom-player side of the fix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/366)
> fix: Ensure that shuffled letters in words look shuffled (BL-14446)

- .github/workflows/release.yml
- README.md
- package.json
- src/activities/activityManager.ts
- src/shared/index.ts
- src/vite-env.d.ts
- tsconfig.json
- vite.config.ts
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/368)
> Emit shared library (BL-14493)

- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/370)
> fix: Allow videos to actually be dragged in games (BL-14599)

- src/shared/dragActivityRuntime.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/371)
> fix: Handle unmoved items in drag game showCorrect function (BL-14600)

- src/shared/dragActivityRuntime.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/373)
> feat: Add exported getAudioSentencesOfVisibleEditables (BL-14717)

- src/shared/dragActivityRuntime.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/374)
> fix: Target divs are not recordable for audio (BL-14756)

- src/shared/narration.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/376)
> fix: Prevent missing audio from wiping out game header styling (BL-14797)

- src/shared/dragActivityRuntime.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/378)
> fix: Handle distractors in showCorrect (BL-14816)

- src/activities/activityManager.ts
- src/activities/dragActivities/DragToDestination.ts
- src/shared/dragActivityRuntime.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/381)
> feat: send simple analytics for draggable games (BL-14796)

- package.json
- src/bloom-player-core.tsx
- src/bloom-player-ui.less
- src/bloom-player-version-control.tsx
- src/l10n/en/messages.json
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/382)
> feat: warn if the book contains an unmet feature requirement (BL-14865)

- src/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/383)
> fix: BL-14817 make hyperlinks work in games

- README-advanced.md
- README.md
- src/shared/ReadMe.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/385)
> chore: Update readme files to cover sharing functions in code (BL-15089)

- src/shared/dragActivityRuntime.ts
This change to bloom-player may be needed by Bloom 6.2.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/388)
> fix: Retrieve the active language data for Order Word games (BL-15175)

- src/video.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/392)
> fix: Show first frame of video sooner (BL-14077)

- src/bloom-player-core.tsx
- src/shared/animation.ts
- src/shared/narration.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/390)
> fix: Improve audio playback during motion (BL-15210, BL-15020)

- src/bloom-player-core.tsx
- src/video.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-player/395)
> fix: another try at getting video to show on page load (BL-14077)
